import {
  User,
  StaffProfile,
  RentalProfile,
  RoomType,
  Room,
  Contract,
  Bill,
  PaymentSlip,
  RepairRequest,
  Announcement,
  SiteContent,
} from "@/types/dormitory";

export const initialUsers: User[] = [
  {
    id: "user-owner-1",
    role: "staff",
    full_name: "คุณสมศักดิ์ วาณิชย์กิจ (เจ้าของหอพัก)",
    phone: "081-999-8888",
    email: "owner@dormitory.com",
    password: "owner1234",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    created_at: "2025-01-01T08:00:00Z",
  },
  {
    id: "user-staff-1",
    role: "staff",
    full_name: "คุณนิตยา ดูแลสุข (นิติบุคคล)",
    phone: "082-123-4567",
    email: "staff@dormitory.com",
    password: "staff1234",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
    created_at: "2025-01-10T09:00:00Z",
  },
  {
    id: "user-rental-201",
    role: "rental",
    full_name: "นายชญานนท์ รักสงบ",
    phone: "089-765-4321",
    email: "tenant201@gmail.com",
    password: "tenant1234",
    avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    created_at: "2026-01-01T10:00:00Z",
  },
  {
    id: "user-rental-301",
    role: "rental",
    full_name: "นางสาวศิริพร เจริญผล",
    phone: "086-555-1234",
    email: "siriporn.301@gmail.com",
    password: "tenant1234",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    created_at: "2026-02-01T11:00:00Z",
  },
];

export const initialStaffProfiles: StaffProfile[] = [
  {
    id: "staff-profile-1",
    user_id: "user-owner-1",
    is_owner: true,
    position: "เจ้าของหอพัก / ผู้บริหารสูงสุด",
    notes: "มีสิทธิ์สูงสุดทุกฟังก์ชันในระบบ",
  },
  {
    id: "staff-profile-2",
    user_id: "user-staff-1",
    is_owner: false,
    position: "ผู้จัดการนิติบุคคลและดูแลอาคาร",
    notes: "ดูแลงานปฏิบัติการประจำวัน เวลา 08:30 - 18:00 น.",
  },
];

export const initialRoomTypes: RoomType[] = [
  {
    id: "rt-1",
    name: "Studio Standard",
    description: "ห้องสตูดิโอขนาด 28 ตร.ม. พร้อมเฟอร์นิเจอร์บิวท์อิน เตียง 5 ฟุต แอร์ประหยัดไฟเบอร์ 5 ระเบียงส่วนตัว",
    base_price: 4500,
    water_rate: 18,
    electric_rate: 8,
    amenities: [
      "เครื่องปรับอากาศ",
      "เครื่องทำน้ำอุ่น",
      "เตียง 5 ฟุต + ฟูกอย่างดี",
      "ตู้เสื้อผ้าบิวท์อิน",
      "โต๊ะทำงาน + เก้าอี้",
      "ระเบียงซักล้างส่วนตัว",
      "High-speed Wi-Fi",
    ],
    image_url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "rt-2",
    name: "Deluxe Corner Room",
    description: "ห้องมุมขนาด 35 ตร.ม. หน้าต่างกระจก 2 ด้านรับลมและแสงธรรมชาติ พร้อมโซฟาพักผ่อน และตู้เย็น",
    base_price: 5500,
    water_rate: 18,
    electric_rate: 8,
    amenities: [
      "เครื่องปรับอากาศ Inverter",
      "สมาร์ททีวี 43 นิ้ว",
      "ตู้เย็น 2 ประตู",
      "เตียง King Size 6 ฟุต",
      "โซฟาเบดรับแขก",
      "ไมโครเวฟ",
      "เครื่องทำน้ำอุ่นระบบดิจิทัล",
    ],
    image_url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "rt-3",
    name: "1-Bedroom Executive Suite",
    description: "ห้องชุดขนาด 45 ตร.ม. กั้นห้องนอนและห้องนั่งเล่นเป็นสัดส่วน เคาน์เตอร์ครัวและอ่างล้างจาน ประตูดิจิทัล",
    base_price: 7500,
    water_rate: 18,
    electric_rate: 8,
    amenities: [
      "แอร์ 2 เครื่อง (ห้องนอน + นั่งเล่น)",
      "Digital Door Lock ปลอดภัยสูง",
      "เครื่องซักผ้าฝาหน้าในห้อง",
      "เคาน์เตอร์ครัวและ Hood ดูดควัน",
      "สมาร์ททีวี 55 นิ้ว 4K",
      "เตียง King Size พรีเมียม",
    ],
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
  },
];

export const initialRooms: Room[] = [
  {
    id: "room-201",
    room_number: "201",
    room_type_id: "rt-1",
    floor: 2,
    status: "occupied",
    monthly_rent: 4500,
  },
  {
    id: "room-202",
    room_number: "202",
    room_type_id: "rt-1",
    floor: 2,
    status: "available",
    monthly_rent: 4500,
  },
  {
    id: "room-203",
    room_number: "203",
    room_type_id: "rt-2",
    floor: 2,
    status: "available",
    monthly_rent: 5500,
  },
  {
    id: "room-301",
    room_number: "301",
    room_type_id: "rt-1",
    floor: 3,
    status: "occupied",
    monthly_rent: 4500,
  },
  {
    id: "room-302",
    room_number: "302",
    room_type_id: "rt-2",
    floor: 3,
    status: "maintenance",
    monthly_rent: 5500,
  },
  {
    id: "room-401",
    room_number: "401",
    room_type_id: "rt-3",
    floor: 4,
    status: "available",
    monthly_rent: 7500,
  },
  {
    id: "room-402",
    room_number: "402",
    room_type_id: "rt-3",
    floor: 4,
    status: "occupied",
    monthly_rent: 7500,
  },
];

export const initialRentalProfiles: RentalProfile[] = [
  {
    id: "rental-profile-201",
    user_id: "user-rental-201",
    room_id: "room-201",
    id_card_number: "1100500123456",
    emergency_contact: "คุณสายใจ รักสงบ (มารดา)",
    emergency_phone: "081-222-3344",
    status: "active",
  },
  {
    id: "rental-profile-301",
    user_id: "user-rental-301",
    room_id: "room-301",
    id_card_number: "3100600987654",
    emergency_contact: "คุณกิตติศักดิ์ เจริญผล (พี่ชาย)",
    emergency_phone: "089-111-2233",
    status: "active",
  },
];

export const initialContracts: Contract[] = [
  {
    id: "contract-201",
    rental_profile_id: "rental-profile-201",
    room_id: "room-201",
    start_date: "2026-01-01",
    end_date: "2026-12-31",
    move_in_date: "2026-01-05",
    deposit_amount: 9000,
    status: "active",
  },
  {
    id: "contract-301",
    rental_profile_id: "rental-profile-301",
    room_id: "room-301",
    start_date: "2026-02-01",
    end_date: "2027-01-31",
    move_in_date: "2026-02-01",
    deposit_amount: 9000,
    status: "active",
  },
];

export const initialBills: Bill[] = [
  {
    id: "bill-201-current",
    room_id: "room-201",
    rental_profile_id: "rental-profile-201",
    month: 9,
    year: 2026,
    room_fee: 4500,
    water_meter_previous: 120,
    water_meter_current: 128,
    water_units: 8,
    water_fee: 144, // 8 * 18
    electric_meter_previous: 450,
    electric_meter_current: 510,
    electric_units: 60,
    electric_fee: 480, // 60 * 8
    other_fees: 100, // ค่าส่วนกลาง/ขยะ
    total_amount: 5224,
    due_date: "2026-09-15",
    status: "unpaid",
    created_at: "2026-09-01T08:00:00Z",
  },
  {
    id: "bill-201-aug",
    room_id: "room-201",
    rental_profile_id: "rental-profile-201",
    month: 8,
    year: 2026,
    room_fee: 4500,
    water_meter_previous: 112,
    water_meter_current: 120,
    water_units: 8,
    water_fee: 144,
    electric_meter_previous: 395,
    electric_meter_current: 450,
    electric_units: 55,
    electric_fee: 440,
    other_fees: 100,
    total_amount: 5184,
    due_date: "2026-08-15",
    status: "paid",
    created_at: "2026-08-01T08:00:00Z",
  },
  {
    id: "bill-301-current",
    room_id: "room-301",
    rental_profile_id: "rental-profile-301",
    month: 9,
    year: 2026,
    room_fee: 4500,
    water_meter_previous: 200,
    water_meter_current: 210,
    water_units: 10,
    water_fee: 180,
    electric_meter_previous: 610,
    electric_meter_current: 685,
    electric_units: 75,
    electric_fee: 600,
    other_fees: 100,
    total_amount: 5380,
    due_date: "2026-09-15",
    status: "pending_verification",
    created_at: "2026-09-01T08:00:00Z",
  },
];

export const initialPaymentSlips: PaymentSlip[] = [
  {
    id: "slip-301-current",
    bill_id: "bill-301-current",
    slip_image_url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80",
    transfer_amount: 5380,
    transfer_time: "2026-09-02T14:32:00Z",
    status: "pending",
    created_at: "2026-09-02T14:35:00Z",
  },
];

export const initialRepairRequests: RepairRequest[] = [
  {
    id: "repair-1",
    rental_profile_id: "rental-profile-201",
    room_id: "room-201",
    title: "เครื่องปรับอากาศไม่ค่อยเย็นและมีเสียงดังผิดปกติ",
    description: "เปิดทิ้งไว้ 30 นาทีแล้วห้องยังไม่เย็น และมีเสียงพัดลมดังกุกกักเป็นระยะ รบกวนเวลาพักผ่อน",
    category: "เครื่องปรับอากาศ",
    image_urls: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80",
    ],
    priority: "high",
    status: "in_progress",
    staff_comment: "นัดช่างแอร์เข้าตรวจเช็คน้ำยาและมอเตอร์พัดลม วันพฤหัสบดีที่ 10 ก.ย. เวลา 13:00 น.",
    created_at: "2026-09-03T10:15:00Z",
    updated_at: "2026-09-04T09:00:00Z",
  },
  {
    id: "repair-2",
    rental_profile_id: "rental-profile-301",
    room_id: "room-301",
    title: "ก็อกน้ำใต้อ่างล้างหน้ามีน้ำหยดซึมตลอดเวลา",
    description: "ตรวจพบน้ำซึมหยดลงพื้นห้องน้ำ อยากให้ช่างเข้ามาเปลี่ยนซีลยางหรือเปลี่ยนหัวก็อกใหม่",
    category: "ประปา",
    image_urls: [],
    priority: "medium",
    status: "pending",
    staff_comment: "รับเรื่องเรียบร้อย เตรียมอะไหล่ซีลยางจะส่งช่างเข้าดูใน 2 วันทำการ",
    created_at: "2026-09-07T16:20:00Z",
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "แจ้งกำหนดการล้างถังพักน้ำและตรวจสอบระบบประปาประจำปี 2026",
    content: "ทางหอพักจะดำเนินการล้างทำความสะอาดถังพักน้ำขนาดใหญ่บนดาดฟ้าในวันอาทิตย์ที่ 20 กันยายน 2569 ระหว่างเวลา 09:00 - 15:00 น. ในช่วงเวลาดังกล่าวอาจมีน้ำประปาไหลอ่อนหรือไม่ไหลในบางช่วง ขอความกรุณาผู้เช่าทุกห้องสำรองน้ำใช้ล่วงหน้า ขออภัยในความไม่สะดวกครับ",
    priority: "urgent",
    is_pinned: true,
    created_by: "staff-profile-2",
    author_name: "นิตยา ดูแลสุข (นิติบุคคล)",
    created_at: "2026-09-05T09:00:00Z",
  },
  {
    id: "ann-2",
    title: "เปิดให้บริการระบบชำระเงินและแจ้งซ่อมออนไลน์เต็มรูปแบบ",
    content: "เพื่อความสะดวกรวดเร็วของลูกบ้านทุกท่าน ขณะนี้สามารถตรวจสอบบิลรายเดือน สแกน QR PromptPay แนบสลิป และส่งคำร้องแจ้งซ่อมพร้อมติดตามสถานะได้ผ่านเว็บไซต์นี้ตลอด 24 ชั่วโมง ขอบคุณที่ให้ความร่วมมือครับ",
    priority: "normal",
    is_pinned: false,
    created_by: "staff-profile-1",
    author_name: "สมศักดิ์ วาณิชย์กิจ (เจ้าของหอพัก)",
    created_at: "2026-09-01T10:00:00Z",
  },
];

export const initialSiteContent: SiteContent[] = [
  {
    id: "sc-hero",
    section_key: "hero",
    title: "เดอะ สราญรมย์ เรสซิเดนซ์ (The Saranrom Residence)",
    subtitle: "หอพักและอพาร์ตเมนต์รายเดือนระดับพรีเมียม เงียบสงบ ปลอดภัย สะดวกสบาย เดินทางสะดวกใกล้รถไฟฟ้าและสิ่งอำนวยความสะดวกครบครัน",
    content_json: {
      badge: "⭐ เปิดจองห้องพักว่างชั้น 2 และชั้น 4 รับโปรพิเศษ!",
      cta_text: "ดูห้องพักว่าง",
      cta_link: "#rooms",
      secondary_cta_text: "เข้าสู่ระบบลูกบ้าน",
      secondary_cta_link: "/login",
      phone: "081-999-8888",
      line: "@saranrom_dorm",
    },
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    order_index: 1,
    is_active: true,
  },
  {
    id: "sc-amenities",
    section_key: "amenities",
    title: "สิ่งอำนวยความสะดวกที่คัดสรรเพื่อคุณ",
    subtitle: "เติมเต็มการพักผ่อนด้วยมาตรฐานความปลอดภัยและสิ่งอำนวยความสะดวกระดับคอนโดมิเนียม",
    content_json: {
      items: [
        {
          icon: "ShieldCheck",
          title: "ระบบรักษาความปลอดภัย 24 ชม.",
          desc: "CCTV ครอบคลุมทุกชั้น ประตูทางเข้าคีย์การ์ดสองชั้น และระบบ Digital Door Lock แต่ละห้อง",
        },
        {
          icon: "Wifi",
          title: "High-Speed Fiber Wi-Fi",
          desc: "อินเทอร์เน็ตความเร็วสูงแยก Access Point ทุกชั้น สัญญาณแรงทั่วถึง รองรับการทำงานและเรียนออนไลน์",
        },
        {
          icon: "Car",
          title: "ที่จอดรถยนต์และมอเตอร์ไซค์",
          desc: "ที่จอดรถในร่มกว้างขวาง ปลอดภัย พร้อมจุดชาร์จ EV Charger และรปภ. ดูแลพื้นที่",
        },
        {
          icon: "Sparkles",
          title: "โซนซักผ้าหยอดเหรียญ & ตู้น้ำ RO",
          desc: "เครื่องซักผ้า-อบผ้าอุตสาหกรรม และตู้กดน้ำดื่มระบบกรอง RO บริการ 24 ชั่วโมง สะอาดได้มาตรฐาน",
        },
        {
          icon: "Mail",
          title: "Smart Parcel Box ตู้รับพัสดุ",
          desc: "รับพัสดุได้ตลอดวันแม้ไม่อยู่ห้อง หมดกังวลเรื่องพัสดุสูญหายหรือเปียกฝน",
        },
        {
          icon: "Clock",
          title: "บริการนิติบุคคลและทีมช่างประจำ",
          desc: "มีเจ้าหน้าที่ดูแลและช่างประจำหอพัก พร้อมแก้ไขปัญหาและดูแลความสะดวกสบายอย่างรวดเร็ว",
        },
      ],
    },
    order_index: 2,
    is_active: true,
  },
  {
    id: "sc-contact",
    section_key: "contact",
    title: "ทำเลที่ตั้งและการเดินทาง",
    subtitle: "ใจกลางเมือง เชื่อมต่อทุกการเดินทาง ใกล้แหล่งของกินและสถานศึกษาชั้นนำ",
    content_json: {
      address: "128/9 ซอยสุขุมวิท 71 แขวงพระโขนงเหนือ เขตวัฒนา กรุงเทพฯ 10110",
      tel: "081-999-8888, 082-123-4567",
      line: "@saranrom_dorm",
      email: "contact@saranrom-residence.com",
      office_hours: "08:30 - 18:00 น. (เปิดบริการทุกวัน)",
      nearby_places: [
        "BTS พระโขนง (นั่งวิน 3 นาที)",
        "แม็กซ์แวลู สุขุมวิท 71 (เดิน 5 นาที)",
        "มหาวิทยาลัยกรุงเทพ (กล้วยน้ำไท)",
        "โรงพยาบาลสุขุมวิท",
      ],
    },
    image_url: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80",
    order_index: 3,
    is_active: true,
  },
];
